name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout nglview repository
      uses: actions/checkout@v4

    - name: Cache conda
      uses: actions/cache@v4
      env:
        CACHE_NUMBER: 2  # Increase this value to reset cache if .github/nglview-gha.yml has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/nglview-gha.yml') }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install Yarn
      run: corepack enable

    - name: Build labextension
      run: |
        cd js
        npm install
        cd ..

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    # https://github.com/Amber-MD/pytraj/blob/890b5a1f4ae440a4b3dd5e5b3cd1db072f4a3ea9/.github/workflows/python-package-conda.yml#L34C1-L55C11
    - name: Install prerequisite packages
      run: |
        sudo apt-get install -y gfortran libbz2-dev libblas-dev liblapack-dev libfftw3-dev clang cmake-data cmake
    - name: Get latest cpptraj commit hash
      id: get-hash
      run: |
        latest_hash=$(git ls-remote https://github.com/Amber-MD/cpptraj.git refs/heads/master | awk '{print $1}')
        echo "::set-output name=hash::$latest_hash"
    - name: Cache cpptraj
      uses: actions/cache@v4
      with:
        path: ~/cpptraj
        key: ${{ runner.os }}-cpptraj-${{ steps.get-hash.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-cpptraj-
    - name: Install cpptraj
      run: |
        if [ ! -d "$HOME/cpptraj" ]; then
          CWD=$(pwd)
          git clone https://github.com/Amber-MD/cpptraj $HOME/cpptraj
          cd $HOME/cpptraj
          yes | ./configure -shared -openmp gnu
          make libcpptraj -j2
          cd $CWD
        fi

    - name: Run tests
      run: |
        export CPPTRAJHOME=$HOME/cpptraj
        pip install -r ./pip-requirements-ci.txt
        python -m pytest -vs tests --cov=nglview --cov-report=html --disable-pytest-warnings

    - name: Check installation with pip
      run: |
        python setup.py sdist
        pip install dist/*gz
        python -c "import nglview as nv; print(nv.__version__)"